---
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: fetch
          command: |
            . venv/bin/activate
            FETCH_DAYS=0 python fetch.py
      - run:
          name: aggregate
          command: |
            . venv/bin/activate
            python aggregate.py
      - run:
          name: compute
          command: |
            . venv/bin/activate
            python compute.py
      - run:
          name: generate
          command: |
            . venv/bin/activate
            python generate.py
      - run:
          name: commit
          command: |
            . venv/bin/activate
            echo "TODO COMMIT and PUSH prod/all.json"
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
        cron: "23 0 * * *"
    jobs:
      - build
